version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: authly-postgres
    environment:
      POSTGRES_USER: authly
      POSTGRES_PASSWORD: authly_password
      POSTGRES_DB: authly_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - authly-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authly-app
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: authly
      DB_PASSWORD: authly_password
      DB_DATABASE: authly_db
    ports:
      - '3000:3000'
    networks:
      - authly-network
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  authly-network:
    driver: bridge
