name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  validation:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Run tests with coverage
        run: npm run test:cov

      - name: Verify coverage file exists
        run: |
          if [ ! -f "./coverage/lcov.info" ]; then
            echo "❌ Error: coverage/lcov.info not found."
            echo "Ensure Jest outputs 'lcov' and that 'npm run test:cov' generates coverage."
            exit 1
          fi
          echo "✅ Coverage file found: coverage/lcov.info"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: success()
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const fs = require('fs');
            const coveragePath = './coverage/coverage-summary.json';
            
            if (fs.existsSync(coveragePath)) {
              const coverage = JSON.parse(fs.readFileSync(coveragePath, 'utf8'));
              const total = coverage.total;
              
              const comment = `## 📊 Test Coverage Report

| Metric | Coverage |
|--------|----------|
| **Statements** | ${total.statements.pct}% |
| **Branches** | ${total.branches.pct}% |
| **Functions** | ${total.functions.pct}% |
| **Lines** | ${total.lines.pct}% |

${total.statements.pct < 80 ? '⚠️ Coverage is below 80%. Please add more unit tests.' : '✅ Great coverage!'}
`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
